version: '3.8'

services:
  backend:
    build: ./back
    container_name: ai-agent-back
    expose:
      - "8000"
    environment:
      - GIGACHAT_CREDENTIALS=${GIGACHAT_CREDENTIALS}
      - SCOPE=${SCOPE}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - app-network

  frontend:
    build: ./client
    container_name: ai-agent-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/certs:ro
    depends_on:
      - backend
    networks:
      - app-network

  bot:
    build: ./bot
    container_name: ai-agent-bot
    environment:
      - SERVER_URL=${SERVER_URL}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    depends_on:
      - backend
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
