version: '3.8'

services:
  backend:
    build: ./back
    container_name: ai-agent-back
    expose:
      - "8000"  # только для внутренней сети
    environment:
      - GIGACHAT_CREDENTIALS=${GIGACHAT_CREDENTIALS}
      - SCOPE=${SCOPE}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    networks:
      - app-network

  frontend:
    build: ./client
    container_name: ai-agent-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/certs:ro  # монтируем сертификаты (только чтение)
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
