GIGACHAT_CREDENTIALS=GIGACHAT_TOKEN
GIGACHAT_SCOPE=SCOPE

JWT_SECRET=secret
ACCESS_TOKEN_EXPIRE_MINUTES=30
REFRESH_TOKEN_EXPIRE_DAYS=30

CLIENT_URL=http://localhost:5173
DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/helper